#+title: Authorization
#+Author:GAbriel

* authorization in active directory
*access control lists (ACLs)*
- defines permissions on objects and resources

*security descriptors*
- contains ACLs

*security groups*
- primary method for assigning permissions efficiently

* verificando configs de um group
grupo domain admins de exemplo -->
#+begin_src powershell
Get-ADGroup -Identity "Domain Admins"
#+end_src

para pegar somente o distinguished name -->
#+begin_src powershell
$grp = (Get-ADGroup -Identity "Domain Admins").DistinguishedName
#+end_src

pegar o DACL do grupo selecionado -->
#+begin_src powershell
$acl = Get-Acl -Path "AD:\$groupDN"
#+end_src

- O DACL é a lista de ACEs (Access Control Entries).

*IdentityReference* -->
- o user ou grupo que possui a permissão (ex: BUILTIN\Administrators)

*ActiveDirectoryRights* -->
- o que eles podem fazer (ex: GenericRead, WriteProperty, ExtendedRight)

*AccessControlType* -->
- allow ou deny

Veriricando o owner do objeto atual -->
#+begin_src powershell
PS C:\Users\Administrator> $acl.Owner
DC01\Domain Admins
#+end_src

verificar diversos -->
#+begin_src powershell
$acl.Access
#+end_src

verificar a string SDDL (Security Descriptor Definition Language) -->
#+begin_src powershell
$acl.Sddl
#+end_src

* kerberos components
** key distribution Center (KDC)
- it is the core component of kerberos that deals with initial authentication and with the issuing of tickets

it is made up of two specific services -->

*Authentication Server (AS)*

  component that deals with initial authentication

  After verifying the user identity, it generates a *ticket granting ticket (TGT)*. these tickets can then be exchanged for *Service tickets*

*Ticket Granting Server (TGS)*

component responsible for issuing *service tickets* by using the TGT

** realm
- a kerberos realm defines a logical security boundary that contains group of principal (users, services and computers) that trust a specific *key distribution center (KDC)* for authencitacion purposes

  in active directory, a realm is automatically created when a domain is initialized. The kerberos realm is the uppercase version of the AD domain name

  for example, for the domain hexdump.lab, the kerberos realm will be HEXDUMP.LAB

to discover the realm your user is currently is, execute the following command, which print the User PRincipal Name (UPN)

#+begin_src powershell
whoami /upn
#+end_src

you can also use this other command

#+begin_src powershell
klist
#+end_src

** principal
a kerberos principal is a unique identity to which kerberos can assign tickets

there are different types of principals

*user principal*
- represents an individual user in the kerberos realm. this is also known as UPN

*service principal*
- represents a service that requires authentication and authorization to be accessed by its clients

example of services -->
- SMB service
- SQL server
- HTTP serveer
- LDAP server

Services need to register proper service principal names (SPNs) within active directory. once this registrarion has taken place, kerberos can use issue tickets for service access

list out all SPNs registed for dc01 -->
#+begin_src powershell
setspn -L central

        ldap/central.dc01.lab/ForestDnsZones.dc01.lab
        ldap/central.dc01.lab/DomainDnsZones.dc01.lab
            TERMSRV/central.dc01.lab
        DNS/central.dc01.lab
#+end_src

get the SPN of specific user -->
#+begin_src powershell
setspn -L tech.lab
Registered ServicePrincipalNames for CN=tech lab,OU=Matriz,DC=dc01,DC=lab:
#+end_src

set a new SPN for the username tech -->
#+begin_src powershell
setspn -A HTTP/webserver.dc01.lab tech.lab
Checking domain DC=dc01,DC=lab

Registering ServicePrincipalNames for CN=tech lab,OU=Matriz,DC=dc01,DC=lab
        HTTP/webserver.dc01.lab
Updated object
#+end_src

*host principal*
- represents a computer in a kerberos realm

------

Each princiapl has an associated *secret key*, which is used during the key agreement protocol to provide authentication
sets

** ticket granting ticket (TGT)
a ticket granting ticket (tgt) is a kerberos ticket that is used to issue Service Tickets through a key distribution center (KDC)

in secure deployments of kerberos, the TGT is issued aft er proper authentication with the Authentication Server (AS). If the authentication is successful, the KDC will issua a TGT

if the TGT is issued prior to proper authentication, an attack known as AS-RESP Roasting can be performed on the kerberos realm

the TGT  contains various informations, such as:
- User ID
- TGS ID
- Expiration time
- TGS session key
- ticket flags

Notice that the TGT is not sent in clear, but it is encrypted with the KDC secret key. this is used for authentication purposes
